### PR TITLE
Wavmap rewrite

### PR DESCRIPTION
**Pull request by crawfordsm**
Re-writes specpolwavmap and splits out a number of functions include one for splitting the images and correcting the distortion.

### CODE REVIEW

**Comment by knordsieck** [comment]
Steve-

Is there a reason you removed “debug” from the specpolwavmap keywords?

I do see that the copy of reducepoldata in the repository does not use it.   Mine does. Perhaps it is my bad for not updating reducepoldata?

Ken

**Comment by knordsieck** [comment]
Steve-

So I removed debug temporarily from my reducepoldata, and ran wavmap on the 0304 data (newly run through imred), with my previous dbfiles in the sci directory so I wouldn’t have to run specidentify again.  The first observation goes through fine, but the second (the 300-line) crashes out.

Output below, and dbfiles enclosed, in case you need them.

Ken

-khn-oderbolz-55-> python reducepoldata.py 20160304
host: Undefined variable.
host: Undefined variable.
SPECPOLWAVMAP
infilelist=['mxgbpP201603040043.fits', 'mxgbpP201603040044.fits', 'mxgbpP201603040045.fits', 'mxgbpP201603040046.fits', 'mxgbpP201603040047.fits', 'mxgbpP201603040048.fits', 'mxgbpP201603040049.fits', 'mxgbpP201603040050.fits', 'mxgbpP201603040051.fits', 'mxgbpP201603040052.fits', 'mxgbpP201603040053.fits', 'mxgbpP201603040054.fits', 'mxgbpP201603040055.fits', 'mxgbpP201603040056.fits', 'mxgbpP201603040057.fits', 'mxgbpP201603040058.fits', 'mxgbpP201603040059.fits', 'mxgbpP201603040060.fits', 'mxgbpP201603040061.fits', 'mxgbpP201603040062.fits']
linelistlib= automethod=Matchlines function=legendre order=3
logfile=specpol20160304.log

2016-03-08 13:47:12 MESSAGE ------------------------------------------
Starting specpolwavmap

Pysalt Version: v0.5dev

For images: 43 44 45 46 47 48 49 50 51 52 53
  Use Arc    53

For images: 54 55 56 57 58 59 60 61 62
  Use Arc    62
[-989.59216796  996.74579026]

ARC: image 53 GRATING PG0900 GRANG   12.500 ARTIC   25.000 LAMP ThAr
  Split Row:  518

  Wavl coeff rows:  O      13     E       5
  Bottom, top row:  O   62  482   E   47  447

  Slit axis row:    O     262     E     247
  Bottom, top row:  O   28  497   E   11  484

Output file wmxgbpP201603040043.fits
Output file wmxgbpP201603040044.fits
Output file wmxgbpP201603040045.fits
Output file wmxgbpP201603040046.fits
Output file wmxgbpP201603040047.fits
Output file wmxgbpP201603040048.fits
Output file wmxgbpP201603040049.fits
Output file wmxgbpP201603040050.fits
Output file wmxgbpP201603040051.fits
Output file wmxgbpP201603040052.fits
Output file wmxgbpP201603040053.fits
[-953.08293255  959.97518951]

ARC: image 62 GRATING PG0300 GRANG    5.375 ARTIC   10.750 LAMP Ar
  Split Row:  515
2016-03-08 13:47:27 ERROR --------------------------------------------

invalid value encountered in less

2016-03-08 13:47:27 MESSAGE ------------------------------------------
specpolwavmap aborted

Traceback (most recent call last):
  File "reducepoldata.py", line 41, in <module>
    specpolwavmap(infile_list, linelistlib=linelistlib, logfile=logfile)
  File "/d/carol/Synched/software/SALT/polsaltcopy/polsalt/specpolwavmap.py", line 95, in specpolwavmap
    log=log)
  File "/d/carol/Synched/software/SALT/polsaltcopy/polsalt/specpolwavmap.py", line 209, in pol_wave_map
    mask = (y < edgerow_od[o,0] + drow_oc[o]) | (y > edgerow_od[o,1] + drow_oc[o])
FloatingPointError: invalid value encountered in less
-khn-oderbolz-55->

**Comment by crawfordsm** [comment]
@knordsieck In response to the debug comment, two reasons: conflicts between the script and because that is generally bad form to use `debug`.   If you want things to write out, it is better to have a specific option for that (like `save_plots`) rather than using debug which is not very specific. 

@knordsieck I'll take a look at the 304 data but this should be a new issue rather than posting the issue on a closed pull request.   I've created a new issue for this.  however, I've re-writen completely how the files are grouped as this should actually be moved out of the individual tasks.   It makes it harder to maintain them and test issues like this.   So I'll test this when I get done with that pull request.

**Comment by knordsieck** [comment]
Sorry, I still am working on how you would like to communicate.  Should these have both been Issues?  And should I be using a different way to do communications like this message here?

Debug:  I was unaware of any standard use for this flag.  What I wanted was a flag I could turn on in the high-level script when I wanted debugging-related output.  So, maybe “debug_output”?  Just name it, and I will update all my uses of it the next time I am doing updates. (Would that be, like, next week?)

Wavmap error:  So I deduce that you think this is related to how I was grouping files into observations?  And it might work if for now I restricted my work to single observations?  I do need to keep working on evaluating data for commissioning support...

Ken

**Pull request merged**
